// AUTO-GENERATED by scripts/license-gen-keys.mjs - DO NOT EDIT BY HAND.
// Ed25519 public key (SPKI/DER, base64) that verifies trial license keys.
// The matching PRIVATE key lives in the vendor kit (license-admin/) and is
// never committed to git. Rotate by re-running the generator + rebuilding.

export const LICENSE_PUBLIC_SPKI_B64 =
  "MCowBQYDK2VwAyEAaX4OPjy6s77P5Qb16t2rnOR4QqPIFWaPQ7aQ2xfPz4A=";
